# Copyright (c) 2021 ayupy
# This software is released under the MIT License, see LICENSE.

runtime: custom
env: flex
entrypoint: gunicorn -b :8080 main:app
runtime_config:
  python_version: 3
service: web-link-downloade-appengine
